config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "movies#index"

  resources :movies
  resources :people
  
  namespace :api do
    namespace :v1 do
      resources :movies
      resources :people
    end

    # JWT - JSON requests at /api/sign_[in|out]
    devise_for :users, defaults: { format: :json },
                     class_name: 'ApiUser',
                           skip: [:registrations, :invitations,
                                  :passwords, :confirmations,
                                  :unlocks],
                           path: '',
                     path_names: { sign_in: 'login',
                                   sign_out: 'logout' }
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      delete 'logout', to: 'devise/sessions#destroy'
    end
  end

end

app/models/person.rb
class Person < ApplicationRecord

  has_many :roles
  has_many :movies_as_actor,    -> { where(roles: { name: 'Actor/Actress' })}, through: :roles, source: :movie, dependent: :delete_all
  has_many :movies_as_director, -> { where(roles: { name: 'Director' })}, through: :roles, source: :movie, dependent: :delete_all
  has_many :movies_as_producer, -> { where(roles: { name: 'Producer' })}, through: :roles, source: :movie, dependent: :delete_all

  validates :first_name, :last_name, presence: true

  def alias_names
    aliases.join(', ')
  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/api/v1/people_controller.rb
class Api::V1::PeopleController < Api::V1::BaseController
  before_action :authenticate_api_user!, only: [:create, :update, :destroy]
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
    render json: @people
  end

  def show
    render json: @person
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      render json: @person, status: :created
    else
      render json: @person.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    if @person.update(person_params)
      render json: @person, status: :accepted
    else
      render json: @person.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @person.destroy
    render json: { message: 'Person was successfully destroyed.' }, status: :accepted
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(
        :first_name,
        :last_name,
        :aliases => [],
        :movies_as_actor_ids => [],
        :movies_as_director_ids => [],
        :movies_as_producer_ids => []
      )
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person, only: [:edit, :update, :destroy]
  before_action :clean_params, only: [:create, :update]

  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_url, notice: 'Person was successfully created.'
    else
      render :new
    end
  end

  def update
    if @person.update(person_params)
      redirect_to people_url, notice: 'Person was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def clean_params
      params[:person][:aliases].reject!(&:empty?)                if params[:person][:aliases]
      params[:person][:movies_as_actor_ids].reject!(&:empty?)    if params[:person][:movies_as_actor_ids]
      params[:person][:movies_as_director_ids].reject!(&:empty?) if params[:person][:movies_as_director_ids]
      params[:person][:movies_as_producer_ids].reject!(&:empty?) if params[:person][:movies_as_producer_ids]
    end

    def person_params
      params.require(:person).permit(
        :first_name,
        :last_name,
        :aliases => [],
        :movies_as_actor_ids => [],
        :movies_as_director_ids => [],
        :movies_as_producer_ids => []
      )
    end
end

app/helpers/people_helper.rb
module PeopleHelper

  def movies_for_select
    Movie.all.map{|m| ["#{m.title} - #{m.release_year}", m.id]}
  end

  def movies_as_actor(person)
    person.movies_as_actor.map(&:title).join(', ')
  end

  def movies_as_director(person)
    person.movies_as_director.map(&:title).join(', ')
  end

  def movies_as_producer(person)
    person.movies_as_producer.map(&:title).join(', ')
  end

end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div class="alert alert-warning text-center" role="alert">
      <h4><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h4>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :first_name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :first_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :last_name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :aliases, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :aliases, @person.aliases, { include_blank: true }, { multiple: true, class: 'select2-tags form-control' } %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Movies as Actor/Actress', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :movies_as_actor_ids, movies_for_select, {}, { multiple: true, class: 'select2 form-control' }  %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Movies as Director', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :movies_as_director_ids, movies_for_select, {}, { multiple: true, class: 'select2 form-control' }  %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Movies as Producer', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :movies_as_producer_ids, movies_for_select, {}, { multiple: true, class: 'select2 form-control' }  %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <%= form.submit "SAVE", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<h3>EDIT PERSON</h3>
<%= render 'form', person: @person %>
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<div class="row">
  <div class="col-sm">
    <h3>PEOPLE</h3>
  </div>
  <div class="col-sm text-right">
    <%= link_to 'NEW PERSON', new_person_path, class: "btn btn-success" %>
  </div>
</div>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Aliases</th>
      <th>Actor/Actress</th>
      <th>Director</th>
      <th>Producer</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><small><%= person.first_name %></small></td>
        <td><small><%= person.last_name %></small></td>
        <td><small><%= person.alias_names %></small></td>
        <td><small><%= movies_as_actor(person) %></small></td>
        <td><small><%= movies_as_director(person) %></small></td>
        <td><small><%= movies_as_producer(person) %></small></td>
        <td><%= link_to 'Edit', edit_person_path(person), class: "btn btn-outline-danger btn-sm" %></td>
        <td><%= link_to 'Destroy', person_path(person), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-secondary btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h3>NEW PERSON</h3>
<%= render 'form', person: @person %>
<%= link_to 'Back', people_path %>