config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "movies#index"

  resources :movies
  resources :people
  
  namespace :api do
    namespace :v1 do
      resources :movies
      resources :people
    end

    # JWT - JSON requests at /api/sign_[in|out]
    devise_for :users, defaults: { format: :json },
                     class_name: 'ApiUser',
                           skip: [:registrations, :invitations,
                                  :passwords, :confirmations,
                                  :unlocks],
                           path: '',
                     path_names: { sign_in: 'login',
                                   sign_out: 'logout' }
    devise_scope :user do
      get 'login', to: 'devise/sessions#new'
      delete 'logout', to: 'devise/sessions#destroy'
    end
  end

end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many :roles
  has_many :casting,   -> { where(roles: { name: 'Actor/Actress' })}, through: :roles, source: :person, dependent: :delete_all
  has_many :directors, -> { where(roles: { name: 'Director' })}, through: :roles, source: :person, dependent: :delete_all
  has_many :producers, -> { where(roles: { name: 'Producer' })}, through: :roles, source: :person, dependent: :delete_all

  validates :title, presence: true
  validates :release_year, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1900, less_than_or_equal_to: Time.now.year }, length: { is: 4 }

end

app/controllers/api/v1/movies_controller.rb
class Api::V1::MoviesController < Api::V1::BaseController
  before_action :authenticate_api_user!, only: [:create, :update, :destroy]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.all
    render json: @movies
  end

  def show
    render json: @movie
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      render json: @movie, status: :created
    else
      render json: @movie.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    if @movie.update(movie_params)
      render json: @movie, status: :accepted
    else
      render json: @movie.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @movie.destroy
    render json: { message: 'Movie was successfully destroyed.' }, status: :accepted
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(
        :title,
        :release_year,
        :casting_ids => [],
        :director_ids => [],
        :producer_ids => []
      )
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_movie, only: [:edit, :update, :destroy]
  before_action :clean_params, only: [:create, :update]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_url, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to movies_url, notice: 'Movie was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url, notice: 'Movie was successfully destroyed.'
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def clean_params
      params[:movie][:casting_ids].reject!(&:empty?)  if params[:movie][:casting_ids]
      params[:movie][:director_ids].reject!(&:empty?) if params[:movie][:director_ids]
      params[:movie][:producer_ids].reject!(&:empty?) if params[:movie][:producer_ids]
    end

    def movie_params
      params.require(:movie).permit(
        :title,
        :release_year,
        :casting_ids => [],
        :director_ids => [],
        :producer_ids => []
      )
    end
end

app/helpers/movies_helper.rb
module MoviesHelper

  def people_for_select
    Person.all.map{|p| ["#{p.full_name}", p.id]}
  end

  def movie_casting(movie)
    movie.casting.map(&:full_name).join(', ')
  end

  def movie_producers(movie)
    movie.producers.map(&:full_name).join(', ')
  end

  def movie_directors(movie)
    movie.directors.map(&:full_name).join(', ')
  end

end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div class="alert alert-warning text-center" role="alert">
      <h4><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h4>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :title, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :release_year, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.number_field :release_year, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Casting (Actors/Actresses)', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :casting_ids, people_for_select, {}, { multiple: true, class: 'select2 form-control' }  %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Directors', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :director_ids, people_for_select, {}, { multiple: true, class: 'select2 form-control' }  %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label 'Producers', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :producer_ids, people_for_select, {}, { multiple: true, class: 'select2 form-control' }  %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <%= form.submit "SAVE", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h3>EDIT MOVIE</h3>
<%= render 'form', movie: @movie %>
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="row">
  <div class="col-sm">
    <h3>MOVIES</h3>
  </div>
  <div class="col-sm text-right">
    <%= link_to 'NEW MOVIE', new_movie_path, class: "btn btn-success" %>
  </div>
</div>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>TITLE</th>
      <th>YEAR</th>
      <th>CASTIING</th>
      <th>DIRECTORS</th>
      <th>PRODUCERS</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><small><%= movie.title %></small></td>
        <td><small><%= movie.release_year.roman %></small></td>
        <td><small><%= movie_casting(movie) %></small></td>
        <td><small><%= movie_directors(movie) %></small></td>
        <td><small><%= movie_producers(movie) %></small></td>
        <td><%= link_to 'Edit', edit_movie_path(movie), class: "btn btn-outline-secondary btn-sm" %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<h3>NEW MOVIE</h3>
<%= render 'form', movie: @movie %>
<%= link_to 'Back', movies_path %>